stages:
    - prebuild
    - build
    - testing
    - deploy

prebuild:bsd:
    stage: prebuild
    script:
        - gcc --version
        - g++ --version
    tags:
        - rmrf
        - rmrfcode
        - freebsd

prebuild:deb:
    stage: prebuild
    script:
        - gcc --version
        - g++ --version
    tags:
        - rmrf
        - rmrfcode
        - debian

build:bsd:
    stage: build
    dependencies:
        - prebuild:bsd
    script:
        - gmake
    artifacts:
        paths:
            - bin
    tags:
        - rmrf
        - rmrfcode
        - freebsd

build:deb:
    stage: build
    dependencies:
        - prebuild:deb
    script:
        - make
        - dpkg-buildpackage -b -us -uc
    artifacts:
        paths:
            - bin
            - ../rmrf*.deb
            - ../rmrf*.ddeb
            - ../rmrf*.changes
            - ../rmrf*.buildinfo
    tags:
        - rmrf
        - rmrfcode
        - debian

test:bsd:
    stage: testing
    dependencies:
        - build:bsd
    script:
        - echo Successfully tested.

test:deb:
    stage: testing
    dependencies:
        - build:deb
    script:
        - echo Successfully tested.
